"""Creacion de tablas consolidadas

Revision ID: b82252fc77d8
Revises: 
Create Date: 2026-10-05 00:33:22.798496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b82252fc77d8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conductores',
    sa.Column('id_conductor', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('numero_licencia', sa.String(length=50), nullable=False),
    sa.Column('categoria_licencia', sa.String(length=10), nullable=False),
    sa.Column('fecha_vencimiento_licencia', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id_conductor'),
    sa.UniqueConstraint('cedula'),
    sa.UniqueConstraint('numero_licencia')
    )
    op.create_index(op.f('ix_conductores_id_conductor'), 'conductores', ['id_conductor'], unique=False)
    op.create_table('rutas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('zona_sector', sa.String(length=100), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('distancia_estimada', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rutas_id'), 'rutas', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula')
    )
    op.create_index(op.f('ix_usuarios_correo'), 'usuarios', ['correo'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=False),
    sa.Column('tipo_vehiculo', sa.String(length=50), nullable=False),
    sa.Column('fecha_vencimiento_soad', sa.Date(), nullable=True),
    sa.Column('fecha_vencimiento_seguro', sa.Date(), nullable=True),
    sa.Column('fecha_vencimiento_tecnomecanica', sa.Date(), nullable=True),
    sa.Column('kilometraje', sa.Integer(), nullable=False),
    sa.Column('ultimo_mantenimiento', sa.Date(), nullable=True),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiculos_id'), 'vehiculos', ['id'], unique=False)
    op.create_table('asignacion_rutas',
    sa.Column('id_asignacion', sa.Integer(), nullable=False),
    sa.Column('id_ruta', sa.Integer(), nullable=False),
    sa.Column('id_conductor', sa.Integer(), nullable=False),
    sa.Column('id_vehiculo', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_conductor'], ['conductores.id_conductor'], ),
    sa.ForeignKeyConstraint(['id_ruta'], ['rutas.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['id_vehiculo'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id_asignacion')
    )
    op.create_index(op.f('ix_asignacion_rutas_id_asignacion'), 'asignacion_rutas', ['id_asignacion'], unique=False)
    op.create_table('mantenimientos',
    sa.Column('id_mantenimiento', sa.Integer(), nullable=False),
    sa.Column('id_vehiculo', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('tipo_mantenimiento', sa.String(length=100), nullable=False),
    sa.Column('fecha_mantenimiento', sa.Date(), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('kilometraje', sa.Integer(), nullable=False),
    sa.Column('costo', sa.Float(), nullable=False),
    sa.Column('taller_responsable', sa.String(length=150), nullable=False),
    sa.Column('proximo_mantenimiento', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['id_vehiculo'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id_mantenimiento')
    )
    op.create_index(op.f('ix_mantenimientos_id_mantenimiento'), 'mantenimientos', ['id_mantenimiento'], unique=False)
    op.create_table('incidencias',
    sa.Column('id_incidencia', sa.Integer(), nullable=False),
    sa.Column('id_asignacion', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('tipo_incidencia', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['id_asignacion'], ['asignacion_rutas.id_asignacion'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id_incidencia')
    )
    op.create_index(op.f('ix_incidencias_id_incidencia'), 'incidencias', ['id_incidencia'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidencias_id_incidencia'), table_name='incidencias')
    op.drop_table('incidencias')
    op.drop_index(op.f('ix_mantenimientos_id_mantenimiento'), table_name='mantenimientos')
    op.drop_table('mantenimientos')
    op.drop_index(op.f('ix_asignacion_rutas_id_asignacion'), table_name='asignacion_rutas')
    op.drop_table('asignacion_rutas')
    op.drop_index(op.f('ix_vehiculos_id'), table_name='vehiculos')
    op.drop_table('vehiculos')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_correo'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_rutas_id'), table_name='rutas')
    op.drop_table('rutas')
    op.drop_index(op.f('ix_conductores_id_conductor'), table_name='conductores')
    op.drop_table('conductores')
    # ### end Alembic commands ###
